"""Mapeo de nombres de selección a códigos ISO para banderas (flagcdn.com)."""

from typing import Optional
import unicodedata


def _norm(name: str) -> str:
    n = unicodedata.normalize("NFD", name.strip().lower())
    return "".join(c for c in n if unicodedata.category(c) != "Mn")


TEAM_ISO: dict[str, str] = {
    "mexico": "mx",
    "sudafrica": "za",
    "corea del sur": "kr",
    "republica checa": "cz",
    "canada": "ca",
    "bosnia y herzegovina": "ba",
    "estados unidos": "us",
    "paraguay": "py",
    "qatar": "qa",
    "catar": "qa",
    "suiza": "ch",
    "brasil": "br",
    "marruecos": "ma",
    "haiti": "ht",
    "escocia": "gb-sct",
    "australia": "au",
    "turquia": "tr",
    "alemania": "de",
    "curazao": "cw",
    "paises bajos": "nl",
    "japon": "jp",
    "costa de marfil": "ci",
    "ecuador": "ec",
    "suecia": "se",
    "tunez": "tn",
    "espana": "es",
    "cabo verde": "cv",
    "belgica": "be",
    "egipto": "eg",
    "arabia saudita": "sa",
    "uruguay": "uy",
    "iran": "ir",
    "nueva zelanda": "nz",
    "francia": "fr",
    "senegal": "sn",
    "irak": "iq",
    "noruega": "no",
    "argentina": "ar",
    "argelia": "dz",
    "austria": "at",
    "jordania": "jo",
    "portugal": "pt",
    "rep. dem. del congo": "cd",
    "republica democratica del congo": "cd",
    "inglaterra": "gb-eng",
    "croacia": "hr",
    "ghana": "gh",
    "panama": "pa",
    "uzbekistan": "uz",
    "colombia": "co",
    "peru": "pe",
    "chile": "cl",
    "bolivia": "bo",
    "venezuela": "ve",
    "italia": "it",
    "ucrania": "ua",
    "polonia": "pl",
    "serbia": "rs",
    "dinamarca": "dk",
    "grecia": "gr",
    "rumania": "ro",
    "hungria": "hu",
    "republica de irlanda": "ie",
    "irlanda": "ie",
    "gales": "gb-wls",
    "costa rica": "cr",
    "honduras": "hn",
    "el salvador": "sv",
    "guatemala": "gt",
    "nicaragua": "ni",
    "cuba": "cu",
    "jamaica": "jm",
    "trinidad y tobago": "tt",
    "china": "cn",
    "india": "in",
    "indonesia": "id",
    "tailandia": "th",
    "vietnam": "vn",
    "filipinas": "ph",
    "malasia": "my",
    "singapur": "sg",
    "nigeria": "ng",
    "camerun": "cm",
    "mali": "ml",
    "gabon": "ga",
    "angola": "ao",
    "zambia": "zm",
    "zimbabue": "zw",
    "kenia": "ke",
    "uganda": "ug",
    "tanzania": "tz",
    "israel": "il",
    "palestina": "ps",
    "libano": "lb",
    "siria": "sy",
    "emiratos arabes unidos": "ae",
    "kuwait": "kw",
    "oman": "om",
    "bahrein": "bh",
    "yemen": "ye",
    "rusia": "ru",
    "finlandia": "fi",
    "islandia": "is",
    "eslovaquia": "sk",
    "eslovenia": "si",
    "bulgaria": "bg",
    "albania": "al",
    "macedonia del norte": "mk",
    "montenegro": "me",
    "kosovo": "xk",
    "georgia": "ge",
    "armenia": "am",
    "azerbaiyan": "az",
    "kazajistan": "kz",
}


def team_flag_iso(team_name: str) -> Optional[str]:
    return TEAM_ISO.get(_norm(team_name))


def team_flag_url(team_name: str, size: int = 40) -> Optional[str]:
    iso = team_flag_iso(team_name)
    if not iso:
        return None
    return f"https://flagcdn.com/w{size}/{iso}.png"
